apiVersion: apps/v1
kind: Deployment
metadata:
  name: lls-provider-kft
  
spec:
  replicas: 1
  selector:
    matchLabels: { app: lls-provider-kft }
  template:
    metadata:
      labels:    { app: lls-provider-kft }
    
    spec:                     
      serviceAccountName: lls-provider-kft
      containers:
        - name: provider
          image: quay.io/efazal/kfto-remote-provider:amd64
          imagePullPolicy: IfNotPresent
          ports:
            - { name: http, containerPort: 8321 }
